In [ ]:
# Date : 16/07/2024

In [1]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype

dtype('int64')

In [7]:
a.dtype.name

'int64'

In [8]:
a.itemsize

8

In [9]:
type(a)

numpy.ndarray

In [10]:
myList = [1,2,3,4,5]
b = np.array(myList)
b

array([1, 2, 3, 4, 5])

In [12]:
type(b)

numpy.ndarray

In [13]:
b.ndim

1

In [36]:
c = [1,4,65,8,0,23,7,7,2]
d = np.array(c).reshape(3,3)
d

array([[ 1,  4, 65],
       [ 8,  0, 23],
       [ 7,  7,  2]])

In [37]:
d.ndim

2

In [38]:
d.shape

(3, 3)

In [40]:
tup = (1, 4, 9, 12.45, "Shivam", 6620)
e = np.array(tup)
e

array(['1', '4', '9', '12.45', 'Shivam', '6620'], dtype='<U32')

In [41]:
e.dtype

dtype('<U32')

In [42]:
type(e)

numpy.ndarray

In [44]:
arr2d = np.array([[1,2], [2,1]])
arr2d

array([[1, 2],
       [2, 1]])

In [46]:
arr2d.ndim

2

In [50]:
arr3d = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[9,8,7],[6,5,4], [3,2,1]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]])

In [51]:
arr3d.ndim

3

In [52]:
arr3d.shape

(2, 3, 3)

In [ ]:
'''
Array Creation
'''

In [3]:
import numpy as np

arr_arange = np.arange(0, 10, 2)
print("arange:", arr_arange)

arr_array = np.array([1, 2, 3, 4, 5])
print("\narray:", arr_array)

arr_copy = arr_array.copy()
print("\ncopy:", arr_copy)

arr_empty = np.empty((2, 3))
print("\nempty:\n", arr_empty)

arr_linspace = np.linspace(0, 1, 5)
print("\nlinspace:", arr_linspace)

arr_identity = np.identity(3)
print("\nidentity:\n", arr_identity)

arr_ones = np.ones((2, 3))
print("\nones:\n", arr_ones)

arr_zeros = np.zeros((2, 3))
print("\nzeros:\n", arr_zeros)


arange: [0 2 4 6 8]

array: [1 2 3 4 5]

copy: [1 2 3 4 5]

empty:
 [[0. 0. 0.]
 [0. 0. 0.]]

linspace: [0.   0.25 0.5  0.75 1.  ]

identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
'''
Conversion
'''

In [5]:
import numpy as np

arr_array = np.array([1, 2, 3])
arr_float = arr_array.astype(float)
print("astype:", arr_float)

arr_atleast_1d = np.atleast_1d([1, 2, 3])
print("\natleast_1d:", arr_atleast_1d)

arr_atleast_2d = np.atleast_2d([1, 2, 3])
print("\natleast_2d:\n", arr_atleast_2d)

arr_atleast_3d = np.atleast_3d([1, 2, 3])
print("\natleast_3d:\n", arr_atleast_3d)

arr_mat = np.mat([[1, 2], [3, 4]])
print("\nmat:\n", arr_mat)

astype: [1. 2. 3.]

atleast_1d: [1 2 3]

atleast_2d:
 [[1 2 3]]

atleast_3d:
 [[[1]
  [2]
  [3]]]

mat:
 [[1 2]
 [3 4]]


In [ ]:
'''
Manipulation
'''

In [6]:
import numpy as np

arr_array = np.array([1, 2, 3, 4, 5, 6])
arr_split = np.array_split(arr_array, 3)
print("array_split:", arr_split)

arr_concatenate = np.concatenate([arr_array, arr_array])
print("\nconcatenate:", arr_concatenate)

arr_diag = np.diag([1, 2, 3])
print("\ndiagonal:\n", arr_diag)

arr_item = arr_diag.item(4)
print("\nndarray.item:", arr_item)

arr_reshape = arr_array.reshape((2, 3))
print("\nreshape:\n", arr_reshape)

arr_resize = np.resize(arr_array, (2, 3))
print("\nresize:\n", arr_resize)

arr_transpose = arr_diag.T
print("\ntranspose:\n", arr_transpose)

array_split: [array([1, 2]), array([3, 4]), array([5, 6])]

concatenate: [1 2 3 4 5 6 1 2 3 4 5 6]

diagonal:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]

ndarray.item: 2

reshape:
 [[1 2 3]
 [4 5 6]]

resize:
 [[1 2 3]
 [4 5 6]]

transpose:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
'''
Basic Statistics
'''

In [7]:
import numpy as np

arr_cov = np.cov([[1, 2, 3], [4, 5, 6]])
print("cov:\n", arr_cov)

arr_array = np.array([1, 2, 3, 4, 5])
arr_mean = np.mean(arr_array)
print("\nmean:", arr_mean)

arr_std = np.std(arr_array)
print("\nstd:", arr_std)

arr_var = np.var(arr_array)
print("\nvar:", arr_var)

cov:
 [[1. 1.]
 [1. 1.]]

mean: 3.0

std: 1.4142135623730951

var: 2.0


In [11]:
'''
Operations
'''

'\nOperations\n'

In [8]:
import numpy as np

arr_sum = np.sum([1, 2, 3, 4, 5])
print("sum:", arr_sum)

arr_cumsum = np.cumsum([1, 2, 3, 4, 5])
print("\ncumsum:", arr_cumsum)

arr_prod = np.prod([1, 2, 3, 4, 5])
print("\nprod:", arr_prod)

arr_array = np.array([1, 2, 3, 4, 5])
arr_put = arr_array.copy()
arr_put.put([0, 2], [10, 20])
print("\nput:", arr_put)

arr_compress = np.compress([1, 0, 1, 0, 1], [10, 20, 30, 40, 50])
print("\ncompress:", arr_compress)

sum: 15

cumsum: [ 1  3  6 10 15]

prod: 120

put: [10  2 20  4  5]

compress: [10 30 50]


In [ ]:
'''
Basic Algebra
'''

In [9]:
import numpy as np

arr_cross = np.cross([1, 0, 0], [0, 1, 0])
print("cross:", arr_cross)

arr_dot = np.dot([1, 2, 3], [4, 5, 6])
print("\ndot:", arr_dot)

cross: [0 0 1]

dot: 32


In [ ]:
# Date : 23/07/2024

In [43]:
# Write a python code to store the given values in tuples and display in 
# the given format by using the user defined function named 'printString'

template = "{0:s} has {1:.2f}% in the class {2:s}"
print("Template string : ", template)

def printString(str, tup):
    print(str.format(tup[0], tup[1], tup[2]))

listTuple = [
    ("Amit", 45, "TY"),
    ("Sumit", 25, "SY"),
    ("Anita", 24, "FY")
]

for item in listTuple:
    printString(template, item)

Template string :  {0:s} has {1:.2f}% in the class {2:s}
Amit has 45.00% in the class TY
Sumit has 25.00% in the class SY
Anita has 24.00% in the class FY


In [57]:
a = [i for i in range(5)]
b = range(5)
c = range(0,10)

print(a)
print(b)
print(c)

[0, 1, 2, 3, 4]
range(0, 5)
range(0, 10)


In [64]:
d = list(range(5))
print(d)

print(list(range(0, 20, 2)))

print(list(range(5, 0, -1)))

[0, 1, 2, 3, 4]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[5, 4, 3, 2, 1]


In [67]:
# Write a python code to store and display the square of odd numbers upto 10. 
# Generate th odd number using range function.

list = []
for i in range(1, 10, 2):
    list.append(i*i)

print(list)

[1, 9, 25, 49, 81]


In [35]:
# Create a python dictionary from the given sequences.
# Sequences:
# keyList =['fy','sy','ty']
# vlaueList=[[1,2,3],[4,5,6],[7,8,9]]

keyList =['fy','sy','ty']
valueList=[[1,2,3],[4,5,6],[7,8,9]]

myDict = {}
for key, value in zip(keyList, valueList):
    myDict[key] = value

print("Dict : ", myDict)
print("keys : ",myDict.keys())
print("values : ", myDict.values())

myDict.update({'ty':[11,21,31]})
print("Dict after updation : ", myDict)

print("Dict after poping 'sy' : ", myDict.pop('sy'))

Dict :  {'fy': [1, 2, 3], 'sy': [4, 5, 6], 'ty': [7, 8, 9]}
keys :  dict_keys(['fy', 'sy', 'ty'])
values :  dict_values([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Dict after updation :  {'fy': [1, 2, 3], 'sy': [4, 5, 6], 'ty': [11, 21, 31]}
Dict after poping 'sy' :  [4, 5, 6]


In [ ]:
print("Keys : ", myDict.keys())
print("Values : ", myDict.values())

myDict['ty'] = [11,12,13]
print(myDict)

print("Poped value for key 'sy': ", myDict.pop('sy'))
print(myDict)

In [3]:
# for the following data create the dictionary of the alpha bitwise list of fruits
# ['apple', 'banana', 'blue berry', 'apricot', 'orange', 'pine apple']
# Expected output

expectOutput = { 'a': ['apple', 'appricot'],
  'b': ['banana', 'blue berry'], 
  'o': ['orange'], 
  'p': ['pine apple']
}

fruits = ['apple', 'banana', 'blue berry', 'appricot', 'orange', 'pine apple']
fruitDict = {}
for fruit in fruits:
    letter = fruit[0]
    if letter not in fruitDict:
        fruitDict[letter] = [fruit]
    else:
        fruitDict[letter].append(fruit)

fruitDict

{'a': ['apple', 'appricot'],
 'b': ['banana', 'blue berry'],
 'o': ['orange'],
 'p': ['pine apple']}

In [19]:
str = "6620_Shivam"
print("str data type: ", type(str))

encode_str = a.encode('utf-8')
print("\nEncoded str : ", encode_str)
print("Encoded str Data type : ", type(encode_str))

decode_str = b.decode('utf-8')
print("\nDecode str : ", decode_str)
print("Decode str Data type : ", type(decode_str))

str data type:  <class 'str'>

Encoded str :  b'6620_Shivam'
Encoded str Data type :  <class 'bytes'>

Decode str :  6620_Shivam
Decode str Data type :  <class 'str'>


In [20]:
roll_no = [6620, 6621, 6622]
name = ["Shivam","Random","Other"]
print("Zipped : ", list(zip(roll_no, name)))

Zipped :  [(6620, 'Shivam'), (6621, 'Random'), (6622, 'Other')]


In [22]:
# Sets
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7}

a.add(10)
print("a : " , a)
a.remove(10)
print("a : " , a)

print("Union : ", a.union(b)) # a | b
print("a : " , a)
a.update(b) # a |= b
print("a : " , a)
print("Interscetion : ", a.intersection(b)) # a & b
a.intersection_update(b) # a &= b
print("a : " , a)

print("Resetting a")
a = {1, 2, 3, 4, 5}

a :  {1, 2, 3, 4, 5, 10}
a :  {1, 2, 3, 4, 5}
Union :  {1, 2, 3, 4, 5, 6, 7}
a :  {1, 2, 3, 4, 5}
a :  {1, 2, 3, 4, 5, 6, 7}
Interscetion :  {3, 4, 5, 6, 7}
a :  {3, 4, 5, 6, 7}
Resetting a


In [27]:
# Define sets a and b
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8, 9}

# Print the initial sets
print('a : ', a)
print('b : ', b)

# Adds an element to the set
a.add(8)
print('a.add(8) : ', a)

# Removes a specific element from the set
a.remove(4)
print('a.remove(4) : ', a)

# Removes and returns an arbitrary element from the set
# You cannot predict which element will be removed
a.pop()
print('a.pop() : ', a)

# New set containing all elements from set a and set b
print('a.union(b) : ', a.union(b))

# Adds all elements from set b to set a
a.update(b)
print('a.update(b) : ', a)

# New set containing elements that are common to both sets
print('a.intersection(b) : ', a.intersection(b))

# Updates set a to contain only elements that are common to both sets a and b
a.intersection_update(b)
print('a.intersection_update(b) : ', a)

# New set containing elements that are in set a but not in set b
a.difference(b)
print('a.difference(b) : ', a)

# Updates set a to remove elements that are also in set b
a = {1, 2, 3, 4, 5}
a.difference_update(b)
print("a.difference_update(b)) : ", a)

# New set containing elements that are in either set a or set b but not in both
print("a.symmetric_difference(b) : ", a.symmetric_difference(b))

# Updates set a to contain elements that are in either set a or set b but not in both
a.symmetric_difference_update(b)
print("a.symmetric_difference_update(b) : ", a)

# Checks if all elements of set a are contained in set b
print("a.issubset(b) : ", a.issubset(b))

# Checks if set a contains all elements of set b
print("a.issuperset(b) : ", a.issuperset(b))

# Checks if sets a and b have no elements in common
print("a.isdisjoint(b) : ", a.isdisjoint(b))

a :  {1, 2, 3, 4, 5}
b :  {3, 4, 5, 6, 7, 8, 9}
a.add(8) :  {1, 2, 3, 4, 5, 8}
a.remove(4) :  {1, 2, 3, 5, 8}
a.pop() :  {2, 3, 5, 8}
a.union(b) :  {2, 3, 4, 5, 6, 7, 8, 9}
a.update(b) :  {2, 3, 4, 5, 6, 7, 8, 9}
a.intersection(b) :  {3, 4, 5, 6, 7, 8, 9}
a.intersection_update(b) :  {3, 4, 5, 6, 7, 8, 9}
a.difference(b) :  {3, 4, 5, 6, 7, 8, 9}
a.difference_update(b)) :  {1, 2}
a.symmetric_difference(b) :  {1, 2, 3, 4, 5, 6, 7, 8, 9}
a.symmetric_difference_update(b) :  {1, 2, 3, 4, 5, 6, 7, 8, 9}
a.issubset(b) :  False
a.issuperset(b) :  True
a.isdisjoint(b) :  False


In [1]:
# 8, 9, 11, 23, 34, 10
# From the given list sum the elements thtabare greater tha 10

list1 = [8, 9, 11, 23, 34, 10]
sum([i for i in list1 if i > 10])

68

In [36]:
strList = ["Bharati", "Aasha", "Easy", "Code"]
set(len(item) for item in strList)

{4, 5, 7}

In [50]:
def calculate (numList):
    square = [item*item for item in numList]
    cube = [item*item*item for item in numList]
    return square, cube 

numList = [1,2,3,4,5]
square, cube = calculate(numList)
print("Square : ", square)
print("Cube : ", cube)

Square :  [1, 4, 9, 16, 25]
Cube :  [1, 8, 27, 64, 125]


In [ ]:
# Date : 30/07/2024

In [2]:
object = ["Apple", "Bat", "Chicken", "Dumpyard", "Erangel", "Friangi"]

objectLen = dict()

for item in object:
    objectLen[item] = len(item)
    
objectLen

{'Apple': 5, 'Bat': 3, 'Chicken': 7, 'Dumpyard': 8, 'Erangel': 7, 'Friangi': 7}

In [26]:
import re

name = [".Manish      ", "     Hardik4!", "Akshay#$", "Shreelaxmee!", "12Rohan", "An      jana"]

def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[ !$#?.0-9]', '', value)
        value = value.title()
        result.append(value)
    return result
    
clean_strings(name)

['Manish', 'Hardik', 'Akshay', 'Shreelaxmee', 'Rohan', 'Anjana']

In [23]:
add = lambda x:  x+x # One argument
add(5)

10

In [24]:
add = lambda x, y:  x+y # Two argument
add(5, 10)

15

In [25]:
solveQuadEq = lambda a, b, c, x: a*x**2 + b*x + c  # Multi argument
solveQuadEq(5, 6, 7, x = 2)

39

In [ ]:
# PANDAS - 30/07/2024

In [38]:
import pandas as pd

name = pd.Series(
    ['Manish', 'Hardik', 'Akshay', 'Shreelaxmee', 'Rohan', 'Anjana'], 
    index=['a', 'b', 'c', 'd', 'e', 'f']
)
name

a         Manish
b         Hardik
c         Akshay
d    Shreelaxmee
e          Rohan
f         Anjana
dtype: object

In [39]:
data = {
    'roll_no' : [6620, 6621, 6622, 6624, 6625, 6626, 6627, 6628],
    'name': ['shivam', 'ganesh', 'dinesh', 'ramesh', 'dhanesh', 'mayuresh', 'deepesh', 'nilesh'],
    'class': ['MSc-IT','MSc-IT','MSc-IT','MSc-IT','MSc-IT','MSc-IT','MSc-IT','MSc-IT']
}

df = pd.DataFrame(data)
df

roll_no      name   class
0     6620    shivam  MSc-IT
1     6621    ganesh  MSc-IT
2     6622    dinesh  MSc-IT
3     6624    ramesh  MSc-IT
4     6625   dhanesh  MSc-IT
5     6626  mayuresh  MSc-IT
6     6627   deepesh  MSc-IT
7     6628    nilesh  MSc-IT

In [40]:
df.head()

roll_no     name   class
0     6620   shivam  MSc-IT
1     6621   ganesh  MSc-IT
2     6622   dinesh  MSc-IT
3     6624   ramesh  MSc-IT
4     6625  dhanesh  MSc-IT

In [41]:
df.tail()

roll_no      name   class
3     6624    ramesh  MSc-IT
4     6625   dhanesh  MSc-IT
5     6626  mayuresh  MSc-IT
6     6627   deepesh  MSc-IT
7     6628    nilesh  MSc-IT

In [45]:
df.head(3)

roll_no    name   class
0     6620  shivam  MSc-IT
1     6621  ganesh  MSc-IT
2     6622  dinesh  MSc-IT

In [46]:
df.tail(3)

roll_no      name   class
5     6626  mayuresh  MSc-IT
6     6627   deepesh  MSc-IT
7     6628    nilesh  MSc-IT

In [47]:
df.describe()

roll_no
count     8.000000
mean   6624.125000
std       2.900123
min    6620.000000
25%    6621.750000
50%    6624.500000
75%    6626.250000
max    6628.000000

In [42]:
df['name']

0      shivam
1      ganesh
2      dinesh
3      ramesh
4     dhanesh
5    mayuresh
6     deepesh
7      nilesh
Name: name, dtype: object

In [43]:
df.name

0      shivam
1      ganesh
2      dinesh
3      ramesh
4     dhanesh
5    mayuresh
6     deepesh
7      nilesh
Name: name, dtype: object

In [44]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [45]:
df.dtypes

roll_no     int64
name       object
class      object
dtype: object